CREATE TABLE `ai_provider` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`provider` text NOT NULL,
	`provider_user_id` text,
	`api_key` text NOT NULL,
	`key_hash` text,
	`key_label` text,
	`is_active` integer DEFAULT true NOT NULL,
	`is_default` integer DEFAULT false NOT NULL,
	`usage_limit` integer,
	`usage_remaining` integer,
	`current_usage` integer DEFAULT 0,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`last_used_at` integer,
	`access_token` text,
	`refresh_token` text,
	`token_expires_at` integer,
	`supported_models` text,
	`provider_config` text,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
