/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardAiRouteImport } from './routes/dashboard/ai'
import { Route as ProjectsProjectIdWriteRouteImport } from './routes/projects/$projectId/write'
import { Route as ProjectsProjectIdStoryBibleRouteImport } from './routes/projects/$projectId/story-bible'
import { Route as ProjectsProjectIdCanvasRouteImport } from './routes/projects/$projectId/canvas'
import { Route as DashboardProjectProjectIdRouteImport } from './routes/dashboard/project/$projectId'
import { Route as DashboardProjectProjectIdIndexRouteImport } from './routes/dashboard/project/$projectId/index'
import { Route as ProjectsProjectIdStoryBibleStyleRouteImport } from './routes/projects/$projectId/story-bible/style'
import { Route as ProjectsProjectIdStoryBibleBraindumpRouteImport } from './routes/projects/$projectId/story-bible/braindump'
import { Route as DashboardProjectProjectIdSettingsRouteImport } from './routes/dashboard/project/$projectId/settings'
import { Route as DashboardProjectProjectIdOutlineRouteImport } from './routes/dashboard/project/$projectId/outline'
import { Route as DashboardProjectProjectIdCharactersRouteImport } from './routes/dashboard/project/$projectId/characters'
import { Route as ProjectsProjectIdStoryBibleWorldWorldIdRouteImport } from './routes/projects/$projectId/story-bible/world.$worldId'
import { Route as ProjectsProjectIdStoryBiblePlotPlotIdRouteImport } from './routes/projects/$projectId/story-bible/plot.$plotId'
import { Route as ProjectsProjectIdStoryBibleNoteNoteIdRouteImport } from './routes/projects/$projectId/story-bible/note.$noteId'
import { Route as ProjectsProjectIdStoryBibleLoreLoreIdRouteImport } from './routes/projects/$projectId/story-bible/lore.$loreId'
import { Route as ProjectsProjectIdStoryBibleLocationLocationIdRouteImport } from './routes/projects/$projectId/story-bible/location.$locationId'
import { Route as ProjectsProjectIdStoryBibleGroupGroupIdRouteImport } from './routes/projects/$projectId/story-bible/group.$groupId'
import { Route as ProjectsProjectIdStoryBibleCharacterCharacterIdRouteImport } from './routes/projects/$projectId/story-bible/character.$characterId'
import { Route as ProjectsProjectIdStoryBibleChapterChapterIdRouteImport } from './routes/projects/$projectId/story-bible/chapter.$chapterId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const ProjectsProjectIdWriteRoute = ProjectsProjectIdWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdStoryBibleRoute =
  ProjectsProjectIdStoryBibleRouteImport.update({
    id: '/story-bible',
    path: '/story-bible',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCanvasRoute = ProjectsProjectIdCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const DashboardProjectProjectIdRoute =
  DashboardProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectProjectIdIndexRoute =
  DashboardProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const ProjectsProjectIdStoryBibleStyleRoute =
  ProjectsProjectIdStoryBibleStyleRouteImport.update({
    id: '/style',
    path: '/style',
    getParentRoute: () => ProjectsProjectIdStoryBibleRoute,
  } as any)
const ProjectsProjectIdStoryBibleBraindumpRoute =
  ProjectsProjectIdStoryBibleBraindumpRouteImport.update({
    id: '/braindump',
    path: '/braindump',
    getParentRoute: () => ProjectsProjectIdStoryBibleRoute,
  } as any)
const DashboardProjectProjectIdSettingsRoute =
  DashboardProjectProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DashboardProjectProjectIdOutlineRoute =
  DashboardProjectProjectIdOutlineRouteImport.update({
    id: '/outline',
    path: '/outline',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DashboardProjectProjectIdCharactersRoute =
  DashboardProjectProjectIdCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const ProjectsProjectIdStoryBibleWorldWorldIdRoute =
  ProjectsProjectIdStoryBibleWorldWorldIdRouteImport.update({
    id: '/world/$worldId',
    path: '/world/$worldId',
    getParentRoute: () => ProjectsProjectIdStoryBibleRoute,
  } as any)
const ProjectsProjectIdStoryBiblePlotPlotIdRoute =
  ProjectsProjectIdStoryBiblePlotPlotIdRouteImport.update({
    id: '/plot/$plotId',
    path: '/plot/$plotId',
    getParentRoute: () => ProjectsProjectIdStoryBibleRoute,
  } as any)
const ProjectsProjectIdStoryBibleNoteNoteIdRoute =
  ProjectsProjectIdStoryBibleNoteNoteIdRouteImport.update({
    id: '/note/$noteId',
    path: '/note/$noteId',
    getParentRoute: () => ProjectsProjectIdStoryBibleRoute,
  } as any)
const ProjectsProjectIdStoryBibleLoreLoreIdRoute =
  ProjectsProjectIdStoryBibleLoreLoreIdRouteImport.update({
    id: '/lore/$loreId',
    path: '/lore/$loreId',
    getParentRoute: () => ProjectsProjectIdStoryBibleRoute,
  } as any)
const ProjectsProjectIdStoryBibleLocationLocationIdRoute =
  ProjectsProjectIdStoryBibleLocationLocationIdRouteImport.update({
    id: '/location/$locationId',
    path: '/location/$locationId',
    getParentRoute: () => ProjectsProjectIdStoryBibleRoute,
  } as any)
const ProjectsProjectIdStoryBibleGroupGroupIdRoute =
  ProjectsProjectIdStoryBibleGroupGroupIdRouteImport.update({
    id: '/group/$groupId',
    path: '/group/$groupId',
    getParentRoute: () => ProjectsProjectIdStoryBibleRoute,
  } as any)
const ProjectsProjectIdStoryBibleCharacterCharacterIdRoute =
  ProjectsProjectIdStoryBibleCharacterCharacterIdRouteImport.update({
    id: '/character/$characterId',
    path: '/character/$characterId',
    getParentRoute: () => ProjectsProjectIdStoryBibleRoute,
  } as any)
const ProjectsProjectIdStoryBibleChapterChapterIdRoute =
  ProjectsProjectIdStoryBibleChapterChapterIdRouteImport.update({
    id: '/chapter/$chapterId',
    path: '/chapter/$chapterId',
    getParentRoute: () => ProjectsProjectIdStoryBibleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdRouteWithChildren
  '/projects/$projectId/canvas': typeof ProjectsProjectIdCanvasRoute
  '/projects/$projectId/story-bible': typeof ProjectsProjectIdStoryBibleRouteWithChildren
  '/projects/$projectId/write': typeof ProjectsProjectIdWriteRoute
  '/dashboard/project/$projectId/characters': typeof DashboardProjectProjectIdCharactersRoute
  '/dashboard/project/$projectId/outline': typeof DashboardProjectProjectIdOutlineRoute
  '/dashboard/project/$projectId/settings': typeof DashboardProjectProjectIdSettingsRoute
  '/projects/$projectId/story-bible/braindump': typeof ProjectsProjectIdStoryBibleBraindumpRoute
  '/projects/$projectId/story-bible/style': typeof ProjectsProjectIdStoryBibleStyleRoute
  '/dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
  '/projects/$projectId/story-bible/chapter/$chapterId': typeof ProjectsProjectIdStoryBibleChapterChapterIdRoute
  '/projects/$projectId/story-bible/character/$characterId': typeof ProjectsProjectIdStoryBibleCharacterCharacterIdRoute
  '/projects/$projectId/story-bible/group/$groupId': typeof ProjectsProjectIdStoryBibleGroupGroupIdRoute
  '/projects/$projectId/story-bible/location/$locationId': typeof ProjectsProjectIdStoryBibleLocationLocationIdRoute
  '/projects/$projectId/story-bible/lore/$loreId': typeof ProjectsProjectIdStoryBibleLoreLoreIdRoute
  '/projects/$projectId/story-bible/note/$noteId': typeof ProjectsProjectIdStoryBibleNoteNoteIdRoute
  '/projects/$projectId/story-bible/plot/$plotId': typeof ProjectsProjectIdStoryBiblePlotPlotIdRoute
  '/projects/$projectId/story-bible/world/$worldId': typeof ProjectsProjectIdStoryBibleWorldWorldIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/projects/$projectId/canvas': typeof ProjectsProjectIdCanvasRoute
  '/projects/$projectId/story-bible': typeof ProjectsProjectIdStoryBibleRouteWithChildren
  '/projects/$projectId/write': typeof ProjectsProjectIdWriteRoute
  '/dashboard/project/$projectId/characters': typeof DashboardProjectProjectIdCharactersRoute
  '/dashboard/project/$projectId/outline': typeof DashboardProjectProjectIdOutlineRoute
  '/dashboard/project/$projectId/settings': typeof DashboardProjectProjectIdSettingsRoute
  '/projects/$projectId/story-bible/braindump': typeof ProjectsProjectIdStoryBibleBraindumpRoute
  '/projects/$projectId/story-bible/style': typeof ProjectsProjectIdStoryBibleStyleRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdIndexRoute
  '/projects/$projectId/story-bible/chapter/$chapterId': typeof ProjectsProjectIdStoryBibleChapterChapterIdRoute
  '/projects/$projectId/story-bible/character/$characterId': typeof ProjectsProjectIdStoryBibleCharacterCharacterIdRoute
  '/projects/$projectId/story-bible/group/$groupId': typeof ProjectsProjectIdStoryBibleGroupGroupIdRoute
  '/projects/$projectId/story-bible/location/$locationId': typeof ProjectsProjectIdStoryBibleLocationLocationIdRoute
  '/projects/$projectId/story-bible/lore/$loreId': typeof ProjectsProjectIdStoryBibleLoreLoreIdRoute
  '/projects/$projectId/story-bible/note/$noteId': typeof ProjectsProjectIdStoryBibleNoteNoteIdRoute
  '/projects/$projectId/story-bible/plot/$plotId': typeof ProjectsProjectIdStoryBiblePlotPlotIdRoute
  '/projects/$projectId/story-bible/world/$worldId': typeof ProjectsProjectIdStoryBibleWorldWorldIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdRouteWithChildren
  '/projects/$projectId/canvas': typeof ProjectsProjectIdCanvasRoute
  '/projects/$projectId/story-bible': typeof ProjectsProjectIdStoryBibleRouteWithChildren
  '/projects/$projectId/write': typeof ProjectsProjectIdWriteRoute
  '/dashboard/project/$projectId/characters': typeof DashboardProjectProjectIdCharactersRoute
  '/dashboard/project/$projectId/outline': typeof DashboardProjectProjectIdOutlineRoute
  '/dashboard/project/$projectId/settings': typeof DashboardProjectProjectIdSettingsRoute
  '/projects/$projectId/story-bible/braindump': typeof ProjectsProjectIdStoryBibleBraindumpRoute
  '/projects/$projectId/story-bible/style': typeof ProjectsProjectIdStoryBibleStyleRoute
  '/dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
  '/projects/$projectId/story-bible/chapter/$chapterId': typeof ProjectsProjectIdStoryBibleChapterChapterIdRoute
  '/projects/$projectId/story-bible/character/$characterId': typeof ProjectsProjectIdStoryBibleCharacterCharacterIdRoute
  '/projects/$projectId/story-bible/group/$groupId': typeof ProjectsProjectIdStoryBibleGroupGroupIdRoute
  '/projects/$projectId/story-bible/location/$locationId': typeof ProjectsProjectIdStoryBibleLocationLocationIdRoute
  '/projects/$projectId/story-bible/lore/$loreId': typeof ProjectsProjectIdStoryBibleLoreLoreIdRoute
  '/projects/$projectId/story-bible/note/$noteId': typeof ProjectsProjectIdStoryBibleNoteNoteIdRoute
  '/projects/$projectId/story-bible/plot/$plotId': typeof ProjectsProjectIdStoryBiblePlotPlotIdRoute
  '/projects/$projectId/story-bible/world/$worldId': typeof ProjectsProjectIdStoryBibleWorldWorldIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/dashboard/ai'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/projects/$projectId'
    | '/dashboard/'
    | '/dashboard/project/$projectId'
    | '/projects/$projectId/canvas'
    | '/projects/$projectId/story-bible'
    | '/projects/$projectId/write'
    | '/dashboard/project/$projectId/characters'
    | '/dashboard/project/$projectId/outline'
    | '/dashboard/project/$projectId/settings'
    | '/projects/$projectId/story-bible/braindump'
    | '/projects/$projectId/story-bible/style'
    | '/dashboard/project/$projectId/'
    | '/projects/$projectId/story-bible/chapter/$chapterId'
    | '/projects/$projectId/story-bible/character/$characterId'
    | '/projects/$projectId/story-bible/group/$groupId'
    | '/projects/$projectId/story-bible/location/$locationId'
    | '/projects/$projectId/story-bible/lore/$loreId'
    | '/projects/$projectId/story-bible/note/$noteId'
    | '/projects/$projectId/story-bible/plot/$plotId'
    | '/projects/$projectId/story-bible/world/$worldId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/dashboard/ai'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/projects/$projectId'
    | '/dashboard'
    | '/projects/$projectId/canvas'
    | '/projects/$projectId/story-bible'
    | '/projects/$projectId/write'
    | '/dashboard/project/$projectId/characters'
    | '/dashboard/project/$projectId/outline'
    | '/dashboard/project/$projectId/settings'
    | '/projects/$projectId/story-bible/braindump'
    | '/projects/$projectId/story-bible/style'
    | '/dashboard/project/$projectId'
    | '/projects/$projectId/story-bible/chapter/$chapterId'
    | '/projects/$projectId/story-bible/character/$characterId'
    | '/projects/$projectId/story-bible/group/$groupId'
    | '/projects/$projectId/story-bible/location/$locationId'
    | '/projects/$projectId/story-bible/lore/$loreId'
    | '/projects/$projectId/story-bible/note/$noteId'
    | '/projects/$projectId/story-bible/plot/$plotId'
    | '/projects/$projectId/story-bible/world/$worldId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/dashboard/ai'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/projects/$projectId'
    | '/dashboard/'
    | '/dashboard/project/$projectId'
    | '/projects/$projectId/canvas'
    | '/projects/$projectId/story-bible'
    | '/projects/$projectId/write'
    | '/dashboard/project/$projectId/characters'
    | '/dashboard/project/$projectId/outline'
    | '/dashboard/project/$projectId/settings'
    | '/projects/$projectId/story-bible/braindump'
    | '/projects/$projectId/story-bible/style'
    | '/dashboard/project/$projectId/'
    | '/projects/$projectId/story-bible/chapter/$chapterId'
    | '/projects/$projectId/story-bible/character/$characterId'
    | '/projects/$projectId/story-bible/group/$groupId'
    | '/projects/$projectId/story-bible/location/$locationId'
    | '/projects/$projectId/story-bible/lore/$loreId'
    | '/projects/$projectId/story-bible/note/$noteId'
    | '/projects/$projectId/story-bible/plot/$plotId'
    | '/projects/$projectId/story-bible/world/$worldId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/projects/$projectId/write': {
      id: '/projects/$projectId/write'
      path: '/write'
      fullPath: '/projects/$projectId/write'
      preLoaderRoute: typeof ProjectsProjectIdWriteRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/story-bible': {
      id: '/projects/$projectId/story-bible'
      path: '/story-bible'
      fullPath: '/projects/$projectId/story-bible'
      preLoaderRoute: typeof ProjectsProjectIdStoryBibleRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/canvas': {
      id: '/projects/$projectId/canvas'
      path: '/canvas'
      fullPath: '/projects/$projectId/canvas'
      preLoaderRoute: typeof ProjectsProjectIdCanvasRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/dashboard/project/$projectId': {
      id: '/dashboard/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/dashboard/project/$projectId'
      preLoaderRoute: typeof DashboardProjectProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/project/$projectId/': {
      id: '/dashboard/project/$projectId/'
      path: '/'
      fullPath: '/dashboard/project/$projectId/'
      preLoaderRoute: typeof DashboardProjectProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/projects/$projectId/story-bible/style': {
      id: '/projects/$projectId/story-bible/style'
      path: '/style'
      fullPath: '/projects/$projectId/story-bible/style'
      preLoaderRoute: typeof ProjectsProjectIdStoryBibleStyleRouteImport
      parentRoute: typeof ProjectsProjectIdStoryBibleRoute
    }
    '/projects/$projectId/story-bible/braindump': {
      id: '/projects/$projectId/story-bible/braindump'
      path: '/braindump'
      fullPath: '/projects/$projectId/story-bible/braindump'
      preLoaderRoute: typeof ProjectsProjectIdStoryBibleBraindumpRouteImport
      parentRoute: typeof ProjectsProjectIdStoryBibleRoute
    }
    '/dashboard/project/$projectId/settings': {
      id: '/dashboard/project/$projectId/settings'
      path: '/settings'
      fullPath: '/dashboard/project/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/dashboard/project/$projectId/outline': {
      id: '/dashboard/project/$projectId/outline'
      path: '/outline'
      fullPath: '/dashboard/project/$projectId/outline'
      preLoaderRoute: typeof DashboardProjectProjectIdOutlineRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/dashboard/project/$projectId/characters': {
      id: '/dashboard/project/$projectId/characters'
      path: '/characters'
      fullPath: '/dashboard/project/$projectId/characters'
      preLoaderRoute: typeof DashboardProjectProjectIdCharactersRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/projects/$projectId/story-bible/world/$worldId': {
      id: '/projects/$projectId/story-bible/world/$worldId'
      path: '/world/$worldId'
      fullPath: '/projects/$projectId/story-bible/world/$worldId'
      preLoaderRoute: typeof ProjectsProjectIdStoryBibleWorldWorldIdRouteImport
      parentRoute: typeof ProjectsProjectIdStoryBibleRoute
    }
    '/projects/$projectId/story-bible/plot/$plotId': {
      id: '/projects/$projectId/story-bible/plot/$plotId'
      path: '/plot/$plotId'
      fullPath: '/projects/$projectId/story-bible/plot/$plotId'
      preLoaderRoute: typeof ProjectsProjectIdStoryBiblePlotPlotIdRouteImport
      parentRoute: typeof ProjectsProjectIdStoryBibleRoute
    }
    '/projects/$projectId/story-bible/note/$noteId': {
      id: '/projects/$projectId/story-bible/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/projects/$projectId/story-bible/note/$noteId'
      preLoaderRoute: typeof ProjectsProjectIdStoryBibleNoteNoteIdRouteImport
      parentRoute: typeof ProjectsProjectIdStoryBibleRoute
    }
    '/projects/$projectId/story-bible/lore/$loreId': {
      id: '/projects/$projectId/story-bible/lore/$loreId'
      path: '/lore/$loreId'
      fullPath: '/projects/$projectId/story-bible/lore/$loreId'
      preLoaderRoute: typeof ProjectsProjectIdStoryBibleLoreLoreIdRouteImport
      parentRoute: typeof ProjectsProjectIdStoryBibleRoute
    }
    '/projects/$projectId/story-bible/location/$locationId': {
      id: '/projects/$projectId/story-bible/location/$locationId'
      path: '/location/$locationId'
      fullPath: '/projects/$projectId/story-bible/location/$locationId'
      preLoaderRoute: typeof ProjectsProjectIdStoryBibleLocationLocationIdRouteImport
      parentRoute: typeof ProjectsProjectIdStoryBibleRoute
    }
    '/projects/$projectId/story-bible/group/$groupId': {
      id: '/projects/$projectId/story-bible/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/projects/$projectId/story-bible/group/$groupId'
      preLoaderRoute: typeof ProjectsProjectIdStoryBibleGroupGroupIdRouteImport
      parentRoute: typeof ProjectsProjectIdStoryBibleRoute
    }
    '/projects/$projectId/story-bible/character/$characterId': {
      id: '/projects/$projectId/story-bible/character/$characterId'
      path: '/character/$characterId'
      fullPath: '/projects/$projectId/story-bible/character/$characterId'
      preLoaderRoute: typeof ProjectsProjectIdStoryBibleCharacterCharacterIdRouteImport
      parentRoute: typeof ProjectsProjectIdStoryBibleRoute
    }
    '/projects/$projectId/story-bible/chapter/$chapterId': {
      id: '/projects/$projectId/story-bible/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/projects/$projectId/story-bible/chapter/$chapterId'
      preLoaderRoute: typeof ProjectsProjectIdStoryBibleChapterChapterIdRouteImport
      parentRoute: typeof ProjectsProjectIdStoryBibleRoute
    }
  }
}

interface DashboardProjectProjectIdRouteChildren {
  DashboardProjectProjectIdCharactersRoute: typeof DashboardProjectProjectIdCharactersRoute
  DashboardProjectProjectIdOutlineRoute: typeof DashboardProjectProjectIdOutlineRoute
  DashboardProjectProjectIdSettingsRoute: typeof DashboardProjectProjectIdSettingsRoute
  DashboardProjectProjectIdIndexRoute: typeof DashboardProjectProjectIdIndexRoute
}

const DashboardProjectProjectIdRouteChildren: DashboardProjectProjectIdRouteChildren =
  {
    DashboardProjectProjectIdCharactersRoute:
      DashboardProjectProjectIdCharactersRoute,
    DashboardProjectProjectIdOutlineRoute:
      DashboardProjectProjectIdOutlineRoute,
    DashboardProjectProjectIdSettingsRoute:
      DashboardProjectProjectIdSettingsRoute,
    DashboardProjectProjectIdIndexRoute: DashboardProjectProjectIdIndexRoute,
  }

const DashboardProjectProjectIdRouteWithChildren =
  DashboardProjectProjectIdRoute._addFileChildren(
    DashboardProjectProjectIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectProjectIdRoute: typeof DashboardProjectProjectIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectProjectIdRoute: DashboardProjectProjectIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProjectsProjectIdStoryBibleRouteChildren {
  ProjectsProjectIdStoryBibleBraindumpRoute: typeof ProjectsProjectIdStoryBibleBraindumpRoute
  ProjectsProjectIdStoryBibleStyleRoute: typeof ProjectsProjectIdStoryBibleStyleRoute
  ProjectsProjectIdStoryBibleChapterChapterIdRoute: typeof ProjectsProjectIdStoryBibleChapterChapterIdRoute
  ProjectsProjectIdStoryBibleCharacterCharacterIdRoute: typeof ProjectsProjectIdStoryBibleCharacterCharacterIdRoute
  ProjectsProjectIdStoryBibleGroupGroupIdRoute: typeof ProjectsProjectIdStoryBibleGroupGroupIdRoute
  ProjectsProjectIdStoryBibleLocationLocationIdRoute: typeof ProjectsProjectIdStoryBibleLocationLocationIdRoute
  ProjectsProjectIdStoryBibleLoreLoreIdRoute: typeof ProjectsProjectIdStoryBibleLoreLoreIdRoute
  ProjectsProjectIdStoryBibleNoteNoteIdRoute: typeof ProjectsProjectIdStoryBibleNoteNoteIdRoute
  ProjectsProjectIdStoryBiblePlotPlotIdRoute: typeof ProjectsProjectIdStoryBiblePlotPlotIdRoute
  ProjectsProjectIdStoryBibleWorldWorldIdRoute: typeof ProjectsProjectIdStoryBibleWorldWorldIdRoute
}

const ProjectsProjectIdStoryBibleRouteChildren: ProjectsProjectIdStoryBibleRouteChildren =
  {
    ProjectsProjectIdStoryBibleBraindumpRoute:
      ProjectsProjectIdStoryBibleBraindumpRoute,
    ProjectsProjectIdStoryBibleStyleRoute:
      ProjectsProjectIdStoryBibleStyleRoute,
    ProjectsProjectIdStoryBibleChapterChapterIdRoute:
      ProjectsProjectIdStoryBibleChapterChapterIdRoute,
    ProjectsProjectIdStoryBibleCharacterCharacterIdRoute:
      ProjectsProjectIdStoryBibleCharacterCharacterIdRoute,
    ProjectsProjectIdStoryBibleGroupGroupIdRoute:
      ProjectsProjectIdStoryBibleGroupGroupIdRoute,
    ProjectsProjectIdStoryBibleLocationLocationIdRoute:
      ProjectsProjectIdStoryBibleLocationLocationIdRoute,
    ProjectsProjectIdStoryBibleLoreLoreIdRoute:
      ProjectsProjectIdStoryBibleLoreLoreIdRoute,
    ProjectsProjectIdStoryBibleNoteNoteIdRoute:
      ProjectsProjectIdStoryBibleNoteNoteIdRoute,
    ProjectsProjectIdStoryBiblePlotPlotIdRoute:
      ProjectsProjectIdStoryBiblePlotPlotIdRoute,
    ProjectsProjectIdStoryBibleWorldWorldIdRoute:
      ProjectsProjectIdStoryBibleWorldWorldIdRoute,
  }

const ProjectsProjectIdStoryBibleRouteWithChildren =
  ProjectsProjectIdStoryBibleRoute._addFileChildren(
    ProjectsProjectIdStoryBibleRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdCanvasRoute: typeof ProjectsProjectIdCanvasRoute
  ProjectsProjectIdStoryBibleRoute: typeof ProjectsProjectIdStoryBibleRouteWithChildren
  ProjectsProjectIdWriteRoute: typeof ProjectsProjectIdWriteRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdCanvasRoute: ProjectsProjectIdCanvasRoute,
  ProjectsProjectIdStoryBibleRoute:
    ProjectsProjectIdStoryBibleRouteWithChildren,
  ProjectsProjectIdWriteRoute: ProjectsProjectIdWriteRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
