/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteRouteImport } from './routes/write'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as WriteProjectIdRouteImport } from './routes/write/$projectId'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardAiRouteImport } from './routes/dashboard/ai'
import { Route as WriteProjectIdWriteRouteImport } from './routes/write/$projectId/write'
import { Route as WriteProjectIdOutlineRouteImport } from './routes/write/$projectId/outline'
import { Route as WriteProjectIdCodexRouteImport } from './routes/write/$projectId/codex'
import { Route as DashboardProjectProjectIdRouteImport } from './routes/dashboard/project/$projectId'
import { Route as DashboardProjectProjectIdIndexRouteImport } from './routes/dashboard/project/$projectId/index'
import { Route as WriteProjectIdCodexTypeRouteImport } from './routes/write/$projectId/codex/$type'
import { Route as DashboardProjectProjectIdWriteRouteImport } from './routes/dashboard/project/$projectId/write'
import { Route as DashboardProjectProjectIdSettingsRouteImport } from './routes/dashboard/project/$projectId/settings'
import { Route as DashboardProjectProjectIdOutlineRouteImport } from './routes/dashboard/project/$projectId/outline'
import { Route as DashboardProjectProjectIdCharactersRouteImport } from './routes/dashboard/project/$projectId/characters'

const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const WriteProjectIdRoute = WriteProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => WriteRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const WriteProjectIdWriteRoute = WriteProjectIdWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => WriteProjectIdRoute,
} as any)
const WriteProjectIdOutlineRoute = WriteProjectIdOutlineRouteImport.update({
  id: '/outline',
  path: '/outline',
  getParentRoute: () => WriteProjectIdRoute,
} as any)
const WriteProjectIdCodexRoute = WriteProjectIdCodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => WriteProjectIdRoute,
} as any)
const DashboardProjectProjectIdRoute =
  DashboardProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectProjectIdIndexRoute =
  DashboardProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const WriteProjectIdCodexTypeRoute = WriteProjectIdCodexTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => WriteProjectIdCodexRoute,
} as any)
const DashboardProjectProjectIdWriteRoute =
  DashboardProjectProjectIdWriteRouteImport.update({
    id: '/write',
    path: '/write',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DashboardProjectProjectIdSettingsRoute =
  DashboardProjectProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DashboardProjectProjectIdOutlineRoute =
  DashboardProjectProjectIdOutlineRouteImport.update({
    id: '/outline',
    path: '/outline',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)
const DashboardProjectProjectIdCharactersRoute =
  DashboardProjectProjectIdCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => DashboardProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRouteWithChildren
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/write/$projectId': typeof WriteProjectIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdRouteWithChildren
  '/write/$projectId/codex': typeof WriteProjectIdCodexRouteWithChildren
  '/write/$projectId/outline': typeof WriteProjectIdOutlineRoute
  '/write/$projectId/write': typeof WriteProjectIdWriteRoute
  '/dashboard/project/$projectId/characters': typeof DashboardProjectProjectIdCharactersRoute
  '/dashboard/project/$projectId/outline': typeof DashboardProjectProjectIdOutlineRoute
  '/dashboard/project/$projectId/settings': typeof DashboardProjectProjectIdSettingsRoute
  '/dashboard/project/$projectId/write': typeof DashboardProjectProjectIdWriteRoute
  '/write/$projectId/codex/$type': typeof WriteProjectIdCodexTypeRoute
  '/dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRouteWithChildren
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/write/$projectId': typeof WriteProjectIdRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/write/$projectId/codex': typeof WriteProjectIdCodexRouteWithChildren
  '/write/$projectId/outline': typeof WriteProjectIdOutlineRoute
  '/write/$projectId/write': typeof WriteProjectIdWriteRoute
  '/dashboard/project/$projectId/characters': typeof DashboardProjectProjectIdCharactersRoute
  '/dashboard/project/$projectId/outline': typeof DashboardProjectProjectIdOutlineRoute
  '/dashboard/project/$projectId/settings': typeof DashboardProjectProjectIdSettingsRoute
  '/dashboard/project/$projectId/write': typeof DashboardProjectProjectIdWriteRoute
  '/write/$projectId/codex/$type': typeof WriteProjectIdCodexTypeRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRouteWithChildren
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/write/$projectId': typeof WriteProjectIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdRouteWithChildren
  '/write/$projectId/codex': typeof WriteProjectIdCodexRouteWithChildren
  '/write/$projectId/outline': typeof WriteProjectIdOutlineRoute
  '/write/$projectId/write': typeof WriteProjectIdWriteRoute
  '/dashboard/project/$projectId/characters': typeof DashboardProjectProjectIdCharactersRoute
  '/dashboard/project/$projectId/outline': typeof DashboardProjectProjectIdOutlineRoute
  '/dashboard/project/$projectId/settings': typeof DashboardProjectProjectIdSettingsRoute
  '/dashboard/project/$projectId/write': typeof DashboardProjectProjectIdWriteRoute
  '/write/$projectId/codex/$type': typeof WriteProjectIdCodexTypeRoute
  '/dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/write'
    | '/dashboard/ai'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/write/$projectId'
    | '/dashboard/'
    | '/dashboard/project/$projectId'
    | '/write/$projectId/codex'
    | '/write/$projectId/outline'
    | '/write/$projectId/write'
    | '/dashboard/project/$projectId/characters'
    | '/dashboard/project/$projectId/outline'
    | '/dashboard/project/$projectId/settings'
    | '/dashboard/project/$projectId/write'
    | '/write/$projectId/codex/$type'
    | '/dashboard/project/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/write'
    | '/dashboard/ai'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/write/$projectId'
    | '/dashboard'
    | '/write/$projectId/codex'
    | '/write/$projectId/outline'
    | '/write/$projectId/write'
    | '/dashboard/project/$projectId/characters'
    | '/dashboard/project/$projectId/outline'
    | '/dashboard/project/$projectId/settings'
    | '/dashboard/project/$projectId/write'
    | '/write/$projectId/codex/$type'
    | '/dashboard/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/write'
    | '/dashboard/ai'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/write/$projectId'
    | '/dashboard/'
    | '/dashboard/project/$projectId'
    | '/write/$projectId/codex'
    | '/write/$projectId/outline'
    | '/write/$projectId/write'
    | '/dashboard/project/$projectId/characters'
    | '/dashboard/project/$projectId/outline'
    | '/dashboard/project/$projectId/settings'
    | '/dashboard/project/$projectId/write'
    | '/write/$projectId/codex/$type'
    | '/dashboard/project/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  WriteRoute: typeof WriteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/write/$projectId': {
      id: '/write/$projectId'
      path: '/$projectId'
      fullPath: '/write/$projectId'
      preLoaderRoute: typeof WriteProjectIdRouteImport
      parentRoute: typeof WriteRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/write/$projectId/write': {
      id: '/write/$projectId/write'
      path: '/write'
      fullPath: '/write/$projectId/write'
      preLoaderRoute: typeof WriteProjectIdWriteRouteImport
      parentRoute: typeof WriteProjectIdRoute
    }
    '/write/$projectId/outline': {
      id: '/write/$projectId/outline'
      path: '/outline'
      fullPath: '/write/$projectId/outline'
      preLoaderRoute: typeof WriteProjectIdOutlineRouteImport
      parentRoute: typeof WriteProjectIdRoute
    }
    '/write/$projectId/codex': {
      id: '/write/$projectId/codex'
      path: '/codex'
      fullPath: '/write/$projectId/codex'
      preLoaderRoute: typeof WriteProjectIdCodexRouteImport
      parentRoute: typeof WriteProjectIdRoute
    }
    '/dashboard/project/$projectId': {
      id: '/dashboard/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/dashboard/project/$projectId'
      preLoaderRoute: typeof DashboardProjectProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/project/$projectId/': {
      id: '/dashboard/project/$projectId/'
      path: '/'
      fullPath: '/dashboard/project/$projectId/'
      preLoaderRoute: typeof DashboardProjectProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/write/$projectId/codex/$type': {
      id: '/write/$projectId/codex/$type'
      path: '/$type'
      fullPath: '/write/$projectId/codex/$type'
      preLoaderRoute: typeof WriteProjectIdCodexTypeRouteImport
      parentRoute: typeof WriteProjectIdCodexRoute
    }
    '/dashboard/project/$projectId/write': {
      id: '/dashboard/project/$projectId/write'
      path: '/write'
      fullPath: '/dashboard/project/$projectId/write'
      preLoaderRoute: typeof DashboardProjectProjectIdWriteRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/dashboard/project/$projectId/settings': {
      id: '/dashboard/project/$projectId/settings'
      path: '/settings'
      fullPath: '/dashboard/project/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/dashboard/project/$projectId/outline': {
      id: '/dashboard/project/$projectId/outline'
      path: '/outline'
      fullPath: '/dashboard/project/$projectId/outline'
      preLoaderRoute: typeof DashboardProjectProjectIdOutlineRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
    '/dashboard/project/$projectId/characters': {
      id: '/dashboard/project/$projectId/characters'
      path: '/characters'
      fullPath: '/dashboard/project/$projectId/characters'
      preLoaderRoute: typeof DashboardProjectProjectIdCharactersRouteImport
      parentRoute: typeof DashboardProjectProjectIdRoute
    }
  }
}

interface DashboardProjectProjectIdRouteChildren {
  DashboardProjectProjectIdCharactersRoute: typeof DashboardProjectProjectIdCharactersRoute
  DashboardProjectProjectIdOutlineRoute: typeof DashboardProjectProjectIdOutlineRoute
  DashboardProjectProjectIdSettingsRoute: typeof DashboardProjectProjectIdSettingsRoute
  DashboardProjectProjectIdWriteRoute: typeof DashboardProjectProjectIdWriteRoute
  DashboardProjectProjectIdIndexRoute: typeof DashboardProjectProjectIdIndexRoute
}

const DashboardProjectProjectIdRouteChildren: DashboardProjectProjectIdRouteChildren =
  {
    DashboardProjectProjectIdCharactersRoute:
      DashboardProjectProjectIdCharactersRoute,
    DashboardProjectProjectIdOutlineRoute:
      DashboardProjectProjectIdOutlineRoute,
    DashboardProjectProjectIdSettingsRoute:
      DashboardProjectProjectIdSettingsRoute,
    DashboardProjectProjectIdWriteRoute: DashboardProjectProjectIdWriteRoute,
    DashboardProjectProjectIdIndexRoute: DashboardProjectProjectIdIndexRoute,
  }

const DashboardProjectProjectIdRouteWithChildren =
  DashboardProjectProjectIdRoute._addFileChildren(
    DashboardProjectProjectIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectProjectIdRoute: typeof DashboardProjectProjectIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectProjectIdRoute: DashboardProjectProjectIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface WriteProjectIdCodexRouteChildren {
  WriteProjectIdCodexTypeRoute: typeof WriteProjectIdCodexTypeRoute
}

const WriteProjectIdCodexRouteChildren: WriteProjectIdCodexRouteChildren = {
  WriteProjectIdCodexTypeRoute: WriteProjectIdCodexTypeRoute,
}

const WriteProjectIdCodexRouteWithChildren =
  WriteProjectIdCodexRoute._addFileChildren(WriteProjectIdCodexRouteChildren)

interface WriteProjectIdRouteChildren {
  WriteProjectIdCodexRoute: typeof WriteProjectIdCodexRouteWithChildren
  WriteProjectIdOutlineRoute: typeof WriteProjectIdOutlineRoute
  WriteProjectIdWriteRoute: typeof WriteProjectIdWriteRoute
}

const WriteProjectIdRouteChildren: WriteProjectIdRouteChildren = {
  WriteProjectIdCodexRoute: WriteProjectIdCodexRouteWithChildren,
  WriteProjectIdOutlineRoute: WriteProjectIdOutlineRoute,
  WriteProjectIdWriteRoute: WriteProjectIdWriteRoute,
}

const WriteProjectIdRouteWithChildren = WriteProjectIdRoute._addFileChildren(
  WriteProjectIdRouteChildren,
)

interface WriteRouteChildren {
  WriteProjectIdRoute: typeof WriteProjectIdRouteWithChildren
}

const WriteRouteChildren: WriteRouteChildren = {
  WriteProjectIdRoute: WriteProjectIdRouteWithChildren,
}

const WriteRouteWithChildren = WriteRoute._addFileChildren(WriteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  WriteRoute: WriteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
