name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate PR
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Type check all packages
        run: bun run check-types

      - name: Build all packages
        run: bun run build

      - name: Lint
        run: bun run lint

      - name: Validation Complete
        run: |
          echo "✅ PR Validation Passed!"
          echo "- Type checking: ✅"
          echo "- Build: ✅" 
          echo "- Linting: ✅"
          echo "Ready to merge and deploy to production!"